

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 1.76.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
  - repo: https://github.com/terraform-linters/tflint
    rev: 0.42.2
    hooks:
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--enable-rule=terraform_documented_variables