project_name: scraper
service_name: be
deployment_type: microservice
statements:
      - Databases:
              actions: ["dynamodb:*"]
              effect: "Allow"
              resources:
                    [
                          "arn:aws:dynamodb:*:*:table/scraper-${user_name}-${branch_name}-*",
                    ]
      - Bucket:
              actions: ["s3:*"]
              effect: "Allow"
              resources:
                    [
                          "arn:aws:s3:::scraper-${user_name}-${branch_name}-${bucket_picture_name}",
                    ]
