name: scraper-backend
statements:
    - Pictures:
          actions: ["s3:*"]
          effect: "Allow"
          resources: ["arn:aws:s3:::${name}-${bucket_picture_name}"]
    - Databases:
          actions: ["dynamodb:*"]
          effect: "Allow"
          resources: ["arn:aws:dynamodb:*:*:table/${name}-*"]
